/**
 * TYPE GENERALES
 */
 export const INICIANDO_CONSULTA = 'INICIANDO_CONSULTA';
 export const FINALIZANDO_CONSULTA = 'FINALIZANDO_CONSULTA';
 export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
 export const REGISTRO_ERROR = "REGISTRO_ERROR";
 export const ACTUALIZACION_EXITOSA = "ACTUALIZACION_EXITOSA";
 
 
 
 export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
 export const LOGIN_ERROR = "LOGIN_ERROR";
 export const CERRAR_SESION = "CERRAR_SESION";
 export const OBTENER_USUARIO = "OBTENER_USUARIO";
 
 
 
 /**
  * TYPE DE PRODUCTOS
  */
 
 export const OBTENER_PRODUCTO = "OBTENER_PRODUCTO"; 
 export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS"; 
 export const OBTENER_PRODUCTOS_POR_PAGINAS = "OBTENER_PRODUCTOS_POR_PAGINAS"; 
 export const BUSCAR_PRODUCTOS = "BUSCAR_PRODUCTOS"; 
 export const OBTENER_MARCAS = "OBTENER_MARCAS"; 
 export const OBTENER_UNIDAD_PRESENTACION = "OBTENER_UNIDAD_PRESENTACION"; 
 
 /**
  * TYPE DE PROVEERDORES
  */
 export const OBTENER_PROVEEDORE = "OBTENER_PROVEEDORE";
 export const OBTENER_PROVEEDORES = "OBTENER_PROVEEDORES";
 export const OBTENER_PROVEEDORES_SELECT = "OBTENER_PROVEEDORES_SELECT";
 export const OBTENER_PROVEEDORES_POR_PAGINAS = "OBTENER_PROVEEDORES_POR_PAGINAS"; 
 export const BUSCAR_PROVEEDOR = "BUSCAR_PROVEEDOR"; 
 
  /**
  * TYPE DE CIUDAD Y PROVINCIAS
  */
   export const BUSCAR_CIUDADES = "BUSCAR_CIUDADES"; 
   export const BUSCAR_PROVINCIAS = "BUSCAR_PROVINCIAS"; 
/**
 * TYPE DE CATEGORIAS
 */
 export const OBTENER_CATEGORIA = "OBTENER_CATEGORIA"; 
 export const OBTENER_CATEGORIAS = "OBTENER_CATEGORIAS"; 
 export const ACTUALIZAR_CATEGORIAS = "ACTUALIZAR_CATEGORIAS"; 
 export const OBTENER_CATEGORIAS_POR_PAGINAS = "OBTENER_CATEGORIAS_POR_PAGINAS"; 

 /**
 * TYPE DE SUBCATEGORIAS
 */
  export const OBTENER_SUBCATEGORIA = "OBTENER_SUBCATEGORIA"; 
  export const OBTENER_SUBCATEGORIAS = "OBTENER_SUBCATEGORIAS"; 
  export const ACTUALIZAR_SUBCATEGORIAS = "ACTUALIZAR_SUBCATEGORIAS"; 
  export const OBTENER_SUBCATEGORIAS_POR_PAGINAS = "OBTENER_SUBCATEGORIAS_POR_PAGINAS"; 
 
   /**
 * TYPE DE UNIDAD
 */
    export const OBTENER_UNIDAD = "OBTENER_UNIDAD"; 
    export const OBTENER_UNIDADES = "OBTENER_UNIDADES"; 
    export const ACTUALIZAR_UNIDAD = "ACTUALIZAR_UNIDAD"; 
    export const OBTENER_UNIDAD_POR_PAGINAS = "OBTENER_UNIDAD_POR_PAGINAS"; 
   